Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('99','VENDA EMBARCADA','1',to_date('11/12/15','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('83','VENDA DE PACOTE','1',to_date('21/08/15','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('39','VENDA DE BILHETE ABERTO MANUAL','1',to_date('20/08/13','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('1','VENDA NORMAL','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('2','ALTA FREQUENCIA','0',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('3','VENDA MANUAL','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('4','VENDA HAND HELD','1',null,'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('5','VENDA CENTRAL TELEFONICA','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('6','VENDA CARGO A OUTROS','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('7','VENDA DE RESERVA','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('8','VENDA DE TRANSFERENCIA','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('9','VENDA DE BILHETE ABERTO','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('11','VENDA A DOMICILIO','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('12','VENDA DE INTERNET','1',null,'51',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('15','RESERVA','1',null,'123',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('18','VENDA PRE-PAGA','1',null,'44',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('19','AGENCIA WEB','1',null,'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('49','VENTA PASAJE ABIERTO PREPAGADO','1',to_date('25/04/14','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('73','TPV_VENTA_EXTRAVIADO','1',to_date('25/04/14','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('81','TPV_CAMBIO_VIAJE','1',to_date('25/04/14','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('82','TPV_CONFIRMA_ABIERTO','1',to_date('25/04/14','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('41','CHECKIN REATIVADO','1',to_date('03/07/14','DD/MM/RR'),'1',null);
Insert into TIPO_VENDA (TIPOVENTA_ID,DESCTIPOVENTA,ACTIVO,FECMODIF,USUARIO_ID,INDCONSUMOBOLETO) values ('32','GERA OCD','1',to_date('28/07/14','DD/MM/RR'),'-1',null);
commit;

exit